/**
 * The weekly Director's Brief. Turns the snapshot + recommendations into a short,
 * skimmable markdown report the founder reads in two minutes and approves from.
 */

import type { Kpis } from './metrics';
import type { Recommendation } from './brain';
import { kpis as kpiTargets } from '../config/targets';

function statusVsTarget(value: number, target: number, higherIsBetter: boolean): string {
  if (value === 0) return 'no data yet';
  const good = higherIsBetter ? value >= target : value <= target;
  return good ? 'on target' : 'below target';
}

export function generateBrief(snapshot: Kpis, recs: Recommendation[], periodLabel: string): string {
  const f = snapshot.funnel;

  const kpiLines = [
    { key: 'lead_conversion', val: snapshot.leadConversionPct },
    { key: 'magnet_conversion', val: snapshot.magnetConversionPct },
  ].map((row) => {
    const t = kpiTargets.find((k) => k.key === row.key);
    if (!t) return '';
    return `| ${t.label} | ${row.val}% | ${t.target}% | ${statusVsTarget(row.val, t.target, t.higherIsBetter)} |`;
  });

  const recLines = recs.length
    ? recs
        .map(
          (r, i) =>
            `### ${i + 1}. ${r.title}  \n` +
            `**Category:** ${r.category} · **Confidence:** ${Math.round(r.confidence * 100)}% · **Owner:** ${r.owner}  \n` +
            `**Why:** ${r.hypothesis}  \n` +
            `**Do this:** ${r.action}  \n` +
            `**Expected impact:** ${r.expected_impact}  \n` +
            `**Evidence:** ${r.evidence}  \n` +
            `**Approve?** [ ] yes  [ ] no`,
        )
        .join('\n\n')
    : '_No recommendations this period. Usually means not enough data yet. Keep the traffic flowing._';

  return `# Director's Brief — ${periodLabel}

Auto-generated by the Growth Brain. Numbers first, then the ranked moves. Approve what you like.

## The funnel
- Visitors: ${f.visitors}
- Framework page views: ${f.frameworkViews} → downloads: ${f.frameworkDownloads}
- CTA clicks: ${f.ctaClicks} (calls booked: ${f.callsBooked})
- Leads captured: ${f.leads}
- Events recorded: ${snapshot.eventCount}

## KPIs vs target
| Metric | This period | Target | Status |
|---|---|---|---|
${kpiLines.filter(Boolean).join('\n')}

## Top CTAs
${snapshot.topCtas.length ? snapshot.topCtas.map((c) => `- ${c.event}: ${c.clicks} clicks`).join('\n') : '_none yet_'}

## Top sources
${snapshot.topSources.length ? snapshot.topSources.map((s) => `- ${s.source}: ${s.visitors} visitors`).join('\n') : '_none yet_'}

## Recommended moves (ranked)
${recLines}

---
_Guardrails held: the brain proposes, you dispose. Nothing here has been sent, spent, or published._
`;
}
